apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dep
  namespace: devops-tools
  labels:
    app: jenkins-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      containers:
        - name: jenkins
          image: nginx:1.25.1
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
